language: generic

notifications:
  email: false

sudo: required
services:
  - docker

before_install:
  - docker build -t gastus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gastus/docker-react npm run test -- --coverage

after_success:
  - docker build -t gastus35/docker-react .

  # Login to docker in one command
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push gastus35/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-885049858137"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
