language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gastus:docker-react -f Dockerfile.dev .

script:
  - docker run gastus/docker-react npm run test -- --coverage