language: generic

notifications:
  email: false
  
sudo: required
services:
  - docker

before_install:
  - docker build -t gastus/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gastus/docker-react npm run test -- --coverage